### ISSUE TITLE
Error in deserialize using Observable in 1.1.1

### ISSUE THREAD

**Issue by jmesa-sistel** [dhlab-basel/json2typescript#89]
After update from 1.0.6 to 1.1.1 I have errors

Code:
```
findAll(): Observable<ProcessScreenFieldDTO[]> {
        let params: HttpParams = new HttpParams();
        params = params.append('atl_token', ATL_TOKEN);
        return this.http.get<ProcessScreenFieldDTO[]>(this.pluginResourceUrl, { params: params }).pipe(map(
            (result: ProcessScreenFieldDTO[]) => {
                return globalJsonConvert.deserialize(result, ProcessScreenFieldDTO);
            }
        ));
    }

```
Error:
```
ERROR in src/app/editor/services/field.service.ts(25,9): error TS2322: Type 'Observable<ProcessScreenFieldDTO | ProcessScreenFieldDTO[]>' is not assignable to type 'Observable<ProcessScreenFieldDTO[]>'.
  Type 'ProcessScreenFieldDTO | ProcessScreenFieldDTO[]' is not assignable to type 'ProcessScreenFieldDTO[]'.
    Type 'ProcessScreenFieldDTO' is missing the following properties from type 'ProcessScreenFieldDTO[]': length, pop, push, concat, and 26 more.
```
Workarounds:
a) In this case I have to use deserializeArray to get it working. If I try with an object instead an array I need to use deserializeObject or I will have similar error.
b) Cast the result: return <ProcessScreenFieldDTO[]>globalJsonConvert.deserialize(result, ProcessScreenFieldDTO);

Tested with typescript  3.2.4 & 3.3.3

**Comment by andreas-aeschlimann** [comment]
This is not an issue, but actually a new feature. As we introduced generics within the json2typescript (de)serialization methods, it checks the return type. The compiler throws an error if you don't infer the correct type.

The `deserialize` method does either return an object or an array, because it expects an object or an array as parameter. If you don't like that, you should explicitely use the `deserializeObject` or `deserializeArray` methods, as you stated.

**Comment by jmesa-sistel** [comment]
@andreas-aeschlimann 
> The `deserialize` method does either return an object or an array, because it expects an object or an array as parameter. If you don't like that, you should explicitely use the `deserializeObject` or `deserializeArray` methods, as you stated.

This is not about if I like it or not, just the next code does not work, so deserialize function seems not useful

```
let x: MyClass;
x = globalJsonConvert.deserialize('', MyClass);

```

**Comment by andreas-aeschlimann** [comment]
As I said:

> The `deserialize` method does either return an object or an array

You need to write this:

```
let x: MyClass | MyClass[];
x = globalJsonConvert.deserialize('', MyClass);
```

If you want to force the compiler to absolutely trust you on the type (I don't suggest that!), then you could do something like this:

```
let x: MyClass;
x = <MyClass> globalJsonConvert.deserialize('', MyClass);
```

I would still use `deserializeObject`.

**Comment by jmesa-sistel** [comment]
Yes I have refactor all my code to use `deserializeObject` or `deserializeArray`. I think it is the best and clear solution.
I do not like this solution: `let x: MyClass | MyClass[];`

Anyway thanks a lot for this great library, it is very very useful.

**Comment by andreas-aeschlimann** [comment]
Yes, it forces us to work even more precise.

I know it can be a little bit annoying but in the end it will help reduce errors.

Thanks!
